# Generated by Django 2.0.3 on 2018-04-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cpu', models.IntegerField()),
                ('hd', models.IntegerField()),
                ('mem', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
